{{- if .Values.debug }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-debug-helper
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
data:
  postgresql_password: {{ include "postgresql.password" . }}
  postgresql_admin_password: {{ include "postgresql.adminPassword" . }}
  rabbitmq_password: {{ include "rabbitmq.password" . }}
{{- end }} 