{{- $postgresSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-postgresql" .Release.Name)) }}
{{- $rabbitSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-rabbitmq" .Release.Name)) }}

{{- if and (not .Values.postgresql.auth.existingSecret) (not $postgresSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | default "postgres" | b64enc }}
  password: {{ include "postgresql.password" . }}
  postgres-password: {{ include "postgresql.adminPassword" . }}
  replication-password: {{ include "postgresql.password" . }}
---
{{- end }}
{{- if and (not .Values.rabbitmq.auth.existingSecret) (not $rabbitSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.auth.username | default "guest" | b64enc }}
  password: {{ include "rabbitmq.password" . }}
{{- end }} 