{{- $postgresqlSecretName := printf "%s-postgresql" .Release.Name -}}
{{- $postgresqlSecret := (lookup "v1" "Secret" .Release.Namespace $postgresqlSecretName) -}}
{{- if not $postgresqlSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  postgres-password: {{ include "postgresql.adminPassword" . }}
  password: {{ include "postgresql.password" . }}
  username: {{ .Values.postgresql.auth.username | default "postgres" | b64enc }}
{{- end }}
---
{{- $rabbitmqSecretName := printf "%s-rabbitmq" .Release.Name -}}
{{- $rabbitmqSecret := (lookup "v1" "Secret" .Release.Namespace $rabbitmqSecretName) -}}
{{- if not $rabbitmqSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc }}
  rabbitmq-password: {{ include "rabbitmq.password" . }}
  password: {{ include "rabbitmq.password" . }}
  username: {{ .Values.rabbitmq.auth.username | default "guest" | b64enc }}
  rabbitmq-username: {{ .Values.rabbitmq.auth.username | default "guest" | b64enc }}
{{- end }} 