name: Credential Showcase Traction Adapter CI

on:
  push:
    branches:
      # - main
      - SHOWCASE-90-pipeline-to-build-and-push
    paths:
      - 'packages/credential-showcase-traction-adapter/**'
      - '.github/workflows/credential-showcase-traction-adapter.yml'
      - '.github/workflows/ci-template.yml'
      - '.github/actions/trivy-scan/**'

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      package_name: credential-showcase-traction-adapter
      package_path: packages
      docker_image: credential-showcase-traction-adapter
      sonar_project_key: showcase-adapter
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }} 
      repository_url: ${{ secrets.repository_url }}